In [1]:
import pandas as pd
import numpy as np

# Preprocessing 
EDA is done in a separate notebook.

In [2]:
df = pd.read_csv("ingredients.csv", sep = ";", header=1)
df.dtypes

NDB_No              str
Descrip             str
Energy_kcal         str
Protein_g           str
Saturated_fats_g    str
Fat_g               str
Carb_g              str
Fiber_g             str
Sugar_g             str
Calcium_mg          str
Iron_mg             str
Magnesium_mg        str
Phosphorus_mg       str
Potassium_mg        str
Sodium_mg           str
Zinc_mg             str
Copper_mcg          str
Manganese_mg        str
Selenium_mcg        str
VitC_mg             str
Thiamin_mg          str
Riboflavin_mg       str
Niacin_mg           str
VitB6_mg            str
Folate_mcg          str
VitB12_mcg          str
VitA_mcg            str
VitE_mg             str
VitD2_mcg           str
dtype: object

In [12]:
df["Descrip"].str.lower().str.strip().duplicated().sum()

np.int64(11189)

In [ ]:
df = df.drop_duplicates()
excl = ["Descrip"]
cols_conv = df.columns.difference(excl)
df[cols_conv] = df[cols_conv].apply(
    lambda col: pd.to_numeric(col, errors="coerce")
)

9390
20505

In [21]:
df.describe()

,NDB_No,Energy_kcal,Protein_g,Saturated_fats_g,Fat_g,Carb_g,Fiber_g,Sugar_g,Calcium_mg,Iron_mg,...,VitC_mg,Thiamin_mg,Riboflavin_mg,Niacin_mg,VitB6_mg,Folate_mcg,VitB12_mcg,VitA_mcg,VitE_mg,VitD2_mcg
count,19402.000000,2.049300e+04,20497.000000,2.049100e+04,20487.000000,19779.000000,19779.000000,20497.000000,20495.000000,20489.000000,...,20489.000000,20497.000000,20489.000000,20493.000000,20493.000000,20499.000000,20489.000000,20479.000000,20483.000000,20495.000000
mean,15653.842800,3.331528e+02,20.124311,6.715822e+12,17.146044,33.357652,3.269882,11.648095,105.973945,4.162331,...,12.554297,0.804801,0.524818,4.792271,2.653931,53.259183,1.727854,128.421896,0.994221,7.086704
std,9341.548961,1.589671e+04,963.725063,4.662776e+14,820.364669,1564.403115,152.724109,557.793272,5060.242394,199.051230,...,601.851076,41.944173,31.041431,229.106211,131.413458,2546.556395,83.324019,6164.622742,6.067395,408.814537
min,2.000000,-1.000000e+00,0.000000,-1.000000e+00,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,...,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9057.000000,8.700000e+01,2.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000,8.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,14422.000000,1.840000e+02,8.000000,1.000000e+00,5.000000,9.000000,0.000000,1.000000,18.000000,1.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,6.000000,0.000000,1.000000,0.120000,0.000000
75%,20316.000000,3.310000e+02,20.000000,4.000000e+00,13.000000,33.000000,3.000000,6.000000,60.000000,3.000000,...,2.000000,0.000000,0.000000,5.000000,0.000000,19.000000,1.000000,19.000000,0.490000,0.000000
max,93600.000000,2.275764e+06,137448.000000,4.587130e+16,117151.000000,219889.000000,21471.000000,79567.000000,723976.000000,28482.000000,...,85679.000000,5984.000000,4407.000000,32794.000000,18687.000000,363916.000000,11900.000000,876650.000000,486.000000,48464.000000

In [22]:
df

,NDB_No,Descrip,Energy_kcal,Protein_g,Saturated_fats_g,Fat_g,Carb_g,Fiber_g,Sugar_g,Calcium_mg,...,VitC_mg,Thiamin_mg,Riboflavin_mg,Niacin_mg,VitB6_mg,Folate_mcg,VitB12_mcg,VitA_mcg,VitE_mg,VitD2_mcg
0,6312.0,campbell's red white crm of asparagus soup cond,89.0,2.0,2.000000e+00,6.0,7.0,2.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
1,28000.0,kellogg's eggo mini muffin tops choc chip,300.0,5.0,4.000000e+00,11.0,45.0,1.0,19.0,217.0,...,0.0,0.0,0.0,4.0,0.0,0.0,1.0,326.0,0.00,0.0
2,10877.0,pork cured ham h2o product rump bone-in ln ht...,131.0,21.0,2.000000e+00,5.0,1.0,0.0,1.0,10.0,...,0.0,0.0,0.0,4.0,0.0,2.0,0.0,11.0,0.21,0.0
3,8615.0,cereals rte kellogg's crunchy nut golden honey...,385.0,7.0,1.000000e+00,4.0,83.0,2.0,34.0,20.0,...,20.0,1.0,1.0,16.0,2.0,28.0,5.0,0.0,0.00,3.0
4,42289.0,oil corn and canola,884.0,0.0,8.000000e+00,100.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.84,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20500,NaN,wheat semolina,352.0,11.0,0.000000e+00,1.0,68.0,10.0,2.0,29.0,...,0.0,0.0,0.0,1.0,0.0,26.0,0.0,1.0,0.20,0.0
20501,3133.0,babyfood fruit pears jr,44.0,0.0,0.000000e+00,0.0,12.0,3.0,7.0,8.0,...,22.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0,0.60,0.0
20502,36031.0,denny's onion rings,385.0,5.0,4.000000e+00,22.0,41.0,2.0,5.0,22.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.23,0.0
20503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20504,NaN,TOTAL,2275764.0,137448.0,4.587130e+16,117151.0,219889.0,21471.0,79567.0,723976.0,...,85679.0,5984.0,4407.0,32794.0,18687.0,363916.0,11900.0,876650.0,486.00,48464.0